#!/bin/bash
#SBATCH --job-name=91
#SBATCH --output=/scratch/smrserraoseabr/ESMDA/data/simulations/it0/data_model91
#SBATCH --error=/scratch/smrserraoseabr/ESMDA/data/simulations/it0/data_model91
#SBATCH --time=2:00:00
#SBATCH --mem=1G
#SBATCH --partition=compute
#SBATCH --account=research-ceg-gse
module load 2022r2
a=91
b=/scratch/smrserraoseabr/ESMDA/data/simulations/it0
c=991
python main_darts.py $a $b $c
